### ISSUE TITLE
Duplicate ingame msgs

### ISSUE THREAD

**Issue by bknysnake2016** [cnaude/PurpleIRC-spigot#43]
Hello,

I've looked over the bot file and config file. I can't seem to find why the plugin adds a duplicate msg ingame but works properly on IRC. Any assistance would be appreciated.

Warmest regards,
bknysnake

**Comment by cnaude** [comment]
Please enable debug mode by typing "/irc debug t" then sending a test message. You can disable debug mode with "/irc debug f". The console output should help identify what's causing this.

**Comment by bknysnake2016** [comment]
This is what I'm seeing on console. I tried commenting out the mcmmo chat. Honestly not sure if I'm doing this correct.

`17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [S]Raw message: [IRC]<%NAME%> %MESSAGE%
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] customPrefix before: [IRC]
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] customPrefix after: [IRC]
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] Adding event to queue: [IRC]<bknysnake> test
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-console-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-hero-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-venture-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-ess-helpop:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-discord-chat:true
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-chat-response:false
17.11 19:26:59 [Server] Server thread/INFO [PurpleIRC] [DEBUG] Broadcast All [mcmmo.chat.adminchat]: [bknysnake] [IRC]<bknysnake> test
17.11 19:26:59 [Server] Server thread/INFO [PurpleIRC] [DEBUG] Adding message to broadcast queue: [bknysnake] [IRC]<bknysnake> test
17.11 19:26:59 [Server] Server thread/INFO [bknysnake] [IRC]<bknysnake> test`

**Comment by cnaude** [comment]
> This is what I'm seeing on console. I tried commenting out the mcmmo chat. Honestly not sure if I'm doing this correct.
> 
> `17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [S]Raw message: [IRC]<%NAME%> %MESSAGE%
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] customPrefix before: [IRC]
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] customPrefix after: [IRC]
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] Adding event to queue: [IRC]<bknysnake> test
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-console-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-hero-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-venture-chat:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-ess-helpop:false
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-discord-chat:true
17.11 19:26:58 [Server] listenerPool1-thread18/INFO [PurpleIRC] [DEBUG] [isMessageEnabled] #MineShat:irc-chat-response:false
17.11 19:26:59 [Server] Server thread/INFO [PurpleIRC] [DEBUG] Broadcast All [mcmmo.chat.adminchat]: [bknysnake] [IRC]<bknysnake> test
17.11 19:26:59 [Server] Server thread/INFO [PurpleIRC] [DEBUG] Adding message to broadcast queue: [bknysnake] [IRC]<bknysnake> test
17.11 19:26:59 [Server] Server thread/INFO [bknysnake] [IRC]<bknysnake> test
`

It's likely due to having multiple -chat options enabled in the messages-enabled section of the bot config. This will cause duplicate messages if you the plugin is hooked into another chat plugin like mcmmo.
