### ISSUE TITLE
PlaceholderAPI uncompatibility

### ISSUE THREAD

**Issue by BRUTme** [cnaude/PurpleIRC-spigot#50]
I have found another bug, if I put PlaceholderAPI 2.10.9 into the plugins folder, all text on the IRC looks like this, no real names, there has to be some bug.

[21:48:30] <@MC_SERVER> [%world%] %name% joined the game.
[21:49:24] <@MC_SERVER> [%world%] %name% joined the game.
[21:49:44] <@MC_SERVER> [%world%] <%name%> %message%
[21:50:15] <@MC_SERVER> [%world%] %name% left the game.

**Comment by cnaude** [comment]
That is definitely strange. I know this used to work. I'll see if I can come up with a fix.

**Comment by cnaude** [comment]
I suspect there is an issue with the placeholder api plugin on 1.16.5. I did, however, figure out how it was conflicting with the purpleirc tokens. Please give this version a try. https://jenkins.chrisnaude.com/jenkins/job/PurpleIRC-spigot/358/artifact/target/PurpleIRC.jar

**Comment by BRUTme** [comment]
Yes, this build seems to work properly, although I did not yet  tested the placeholder api itself, Thnx friend :)

**Comment by nerdpower** [comment]
Fyi, I experienced this same issue. IRC was working fine with vanilla game-chat. I added VentureChat, which required PAPI, and the %name% and %message% were no longer replaced with the values.

@cnaude Anything you need us to do to help get this fixed in PAPI? Submit an issue, pile on an issue you've submitted?
